"""
Ingestion configuration module.
This module defines the IngestionConfig dataclass, which encapsulates the configuration settings required for the ingestion process.
The configuration includes parameters for Azure AI Search, Azure AI Services, Azure OpenAI embedding skill, Azure Storage, and chunking settings.
The IngestionConfig class provides a convenient way to load configuration from environment variables, ensuring that all required settings are present and valid.
The class also includes default values for certain parameters, allowing for flexibility in the configuration process.
The from_env class method is responsible for reading the necessary environment variables and constructing an instance of IngestionConfig, raising an error if any required environment variable is missing.
This module is essential for managing the configuration of the ingestion process in a structured and consistent manner, enabling seamless integration with Azure services and efficient document processing workflows.

"""

from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Optional


def _require(key: str) -> str:
    """Run require.

    Args:
        key: The name of the environment variable to retrieve.

    Returns:
        The value of the environment variable.

    Raises:
        ValueError: If the environment variable is not set.
    """
    v = os.environ.get(key)
    if not v:
        raise ValueError(f"Required environment variable not set: {key}")
    return v


@dataclass(frozen=True)
class IngestionConfig:
    # Azure AI Search
    """IngestionConfig.

    Attributes:
        search_endpoint: The endpoint URL for the Azure AI Search service.
        search_index_name: The name of the Azure AI Search index to be used for ingestion.
        data_source_name: The name of the Azure AI Search data source.
        skillset_name: The name of the Azure AI Search skillset to be used for enrichment.
        indexer_name: The name of the Azure AI Search indexer to be used for indexing.
        ai_services_endpoint: The endpoint URL for the Azure AI Services (Foundry) used for skillset enrichment billing via managed identity.
        azure_openai_endpoint: The endpoint URL for the Azure OpenAI embedding skill.
        embedding_deployment_name: The name of the Azure OpenAI embedding deployment.
        embedding_dimensions: The number of dimensions for the embeddings generated by the Azure OpenAI embedding skill.
        storage_account_name: The name of the Azure Storage account to be used for blob storage.
        storage_container_name: The name of the Azure Storage container to be used for blob storage.
        storage_container_query: An optional virtual directory prefix used by the Azure Search data source query.
        storage_resource_id: The ARM resource ID for the managed-identity data source connection.
        chunk_size: The size of each chunk for document processing.
        chunk_overlap: The number of overlapping characters between chunks for document processing.
    """
    search_endpoint: str
    search_index_name: str
    data_source_name: str
    skillset_name: str
    indexer_name: str

    # Azure AI Services (Foundry) — used for skillset enrichment billing via managed identity
    ai_services_endpoint: str

    # Azure OpenAI embedding skill
    azure_openai_endpoint: str
    embedding_deployment_name: str
    embedding_dimensions: int

    # Azure Storage (blob source)
    storage_account_name: str
    storage_container_name: str
    # Optional blob virtual directory prefix used by Azure Search data source
    # query, e.g. "corpus-b/by-dedupe/" or "corpus-c/by-dedupe/".
    storage_container_query: Optional[str]
    # ARM resource ID for managed-identity data source connection, e.g.:
    #   /subscriptions/.../resourceGroups/.../providers/Microsoft.Storage/storageAccounts/name
    # Obtain with: az storage account show -g <rg> -n <name> --query id -o tsv
    storage_resource_id: str

    # Chunking
    chunk_size: int
    chunk_overlap: int

    @classmethod
    def from_env(cls) -> IngestionConfig:
        """Run from env.
        Reads configuration from environment variables and constructs an IngestionConfig instance.

        Args:
            cls: The IngestionConfig class.
        Raises:
            ValueError: If any required environment variable is missing.
        Returns:
            An instance of IngestionConfig populated with values from environment variables.
        """
        index_name = os.environ.get("AZURE_SEARCH_INDEX_NAME", "grounding-index")
        return cls(
            search_endpoint=_require("AZURE_SEARCH_ENDPOINT"),
            search_index_name=index_name,
            data_source_name=os.environ.get(
                "AZURE_SEARCH_DATASOURCE_NAME", f"{index_name}-datasource"
            ),
            skillset_name=os.environ.get("AZURE_SEARCH_SKILLSET_NAME", f"{index_name}-skillset"),
            indexer_name=os.environ.get("AZURE_SEARCH_INDEXER_NAME", f"{index_name}-indexer"),
            ai_services_endpoint=_require("AI_SERVICES_ENDPOINT"),
            azure_openai_endpoint=_require("AZURE_OPENAI_ENDPOINT"),
            embedding_deployment_name=os.environ.get(
                "EMBEDDING_DEPLOYMENT_NAME", "text-embedding-ada-002"
            ),
            embedding_dimensions=int(os.environ.get("EMBEDDING_DIMENSIONS", "1536")),
            storage_account_name=_require("AZURE_STORAGE_ACCOUNT_NAME"),
            storage_container_name=os.environ.get("AZURE_STORAGE_CONTAINER_NAME", "grounding-data"),
            storage_container_query=(
                (os.environ.get("AZURE_STORAGE_CONTAINER_QUERY") or "").strip() or None
            ),
            storage_resource_id=_require("AZURE_STORAGE_RESOURCE_ID"),
            chunk_size=int(os.environ.get("CHUNK_SIZE", "1200")),
            chunk_overlap=int(os.environ.get("CHUNK_OVERLAP", "200")),
        )
