"""
Azure AI Search indexer pipeline manager.

Provisions and runs a server-side enrichment pipeline using Azure AI Search
built-in cognitive skills.  The pipeline replaces client-side document parsing
with server-side processing, which:

  - Handles more formats natively (PDF, DOCX, XLSX, PPTX, HTML and more).
  - Applies OcrSkill for scanned / image-only PDFs.
  - Uses DocumentExtractionSkill for uniform extraction control across formats.
  - Applies MergeSkill to combine native text with OCR text.
  - Uses SplitSkill for server-side chunking (configurable size / overlap).
  - Generates vector embeddings via AzureOpenAIEmbeddingSkill.
  - Projects one Search document per chunk via index projections.

Skill execution flow (per blob document):

  /document/file_data
      └─► DocumentExtractionSkill
              ├─► /document/extracted_content      (native text)
              └─► /document/normalised_images/*    (page images from PDF / raster)
                      └─► OcrSkill
                              └─► /document/normalised_images/*/ocr_text  (OCR text)

  MergeSkill (extracted_content + ocr_text items)
      └─► /document/merged_content

  SplitSkill (merged_content)
      └─► /document/pages/*                        (one item per chunk)

  AzureOpenAIEmbeddingSkill (context: /document/pages/*)
      └─► /document/pages/*/content_vector         (embedding per chunk)

  Index projections (source context: /document/pages/*)
      └─► One Search document per chunk with: content, content_vector,
          source_path, source_name, parent_id

Prerequisites
-------------
- Search service system-assigned managed identity must be enabled.
- That identity requires:
    Storage Blob Data Reader    on the storage account
    Cognitive Services User     on the Foundry / AI Services account (for OcrSkill)
    Cognitive Services OpenAI User  on the Foundry account (for embedding skill)
- If using key-based embedding auth (AZURE_OPENAI_API_KEY set), the MI roles
  for OpenAI are not required for the skill itself but are still recommended
  for runtime query access.
"""
from __future__ import annotations

import logging
import time
from typing import Optional

from azure.core.credentials import TokenCredential
from azure.core.exceptions import ResourceNotFoundError
from azure.search.documents.indexes import SearchIndexClient, SearchIndexerClient
from azure.search.documents.indexes.models import (
    AzureOpenAIEmbeddingSkill,
    BlobIndexerImageAction,
    CognitiveServicesAccountKey,
    DocumentExtractionSkill,
    HnswAlgorithmConfiguration,
    IndexingParameters,
    IndexingParametersConfiguration,
    IndexProjectionMode,
    InputFieldMappingEntry,
    LexicalAnalyzerName,
    MergeSkill,
    OcrSkill,
    OutputFieldMappingEntry,
    SearchField,
    SearchFieldDataType,
    SearchIndex,
    SearchIndexer,
    SearchIndexerDataContainer,
    SearchIndexerDataSourceConnection,
    SearchIndexerDataSourceType,
    SearchIndexerIndexProjectionSelector,
    SearchIndexerIndexProjection,
    SearchIndexerIndexProjectionsParameters,
    SearchIndexerSkillset,
    SemanticConfiguration,
    SemanticField,
    SemanticPrioritizedFields,
    SemanticSearch,
    SimpleField,
    SplitSkill,
    VectorSearch,
    VectorSearchProfile,
)

from .config import IngestionConfig

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Index
# ---------------------------------------------------------------------------

def ensure_search_index(config: IngestionConfig, credential: TokenCredential) -> None:
    """Create or update the target Search index schema."""
    client = SearchIndexClient(endpoint=config.search_endpoint, credential=credential)

    fields = [
        # Chunk-level key generated by index projection.
        SearchField(
            name="id",
            type=SearchFieldDataType.String,
            key=True,
            searchable=True,
            analyzer_name=LexicalAnalyzerName.KEYWORD,
            filterable=True,
        ),
        # Parent document identifier; used for selective deletion on re-index.
        SimpleField(
            name="parent_id",
            type=SearchFieldDataType.String,
            filterable=True,
        ),
        # Chunk text — primary searchable content.
        SearchField(
            name="content",
            type=SearchFieldDataType.String,
            searchable=True,
            analyzer_name="en.microsoft",
        ),
        # Dense vector for semantic / hybrid retrieval.
        SearchField(
            name="content_vector",
            type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
            searchable=True,
            vector_search_dimensions=config.embedding_dimensions,
            vector_search_profile_name="hnsw-profile",
        ),
        # Blob storage path (full URL).
        SimpleField(
            name="source_path",
            type=SearchFieldDataType.String,
            filterable=True,
            retrievable=True,
        ),
        # Original filename.
        SimpleField(
            name="source_name",
            type=SearchFieldDataType.String,
            filterable=True,
            facetable=True,
            retrievable=True,
        ),
    ]

    vector_search = VectorSearch(
        algorithms=[HnswAlgorithmConfiguration(name="hnsw-config")],
        profiles=[VectorSearchProfile(name="hnsw-profile", algorithm_configuration_name="hnsw-config")],
    )

    semantic_search = SemanticSearch(
        configurations=[
            SemanticConfiguration(
                name="default-semantic",
                prioritized_fields=SemanticPrioritizedFields(
                    content_fields=[SemanticField(field_name="content")]
                ),
            )
        ]
    )

    index = SearchIndex(
        name=config.search_index_name,
        fields=fields,
        vector_search=vector_search,
        semantic_search=semantic_search,
    )

    client.create_or_update_index(index)
    logger.info("Search index ensured: %s", config.search_index_name)


# ---------------------------------------------------------------------------
# Data source
# ---------------------------------------------------------------------------

def ensure_data_source(config: IngestionConfig, credential: TokenCredential) -> None:
    """Create or update the blob storage data source using managed identity auth."""
    client = SearchIndexerClient(endpoint=config.search_endpoint, credential=credential)

    # Managed-identity connection string — no credentials stored in code.
    # Requires Search service system-assigned MI to have Storage Blob Data Reader
    # role on the storage account.
    connection_string = f"ResourceId={config.storage_resource_id}"

    data_source = SearchIndexerDataSourceConnection(
        name=config.data_source_name,
        type=SearchIndexerDataSourceType.AZURE_BLOB,
        connection_string=connection_string,
        container=SearchIndexerDataContainer(name=config.storage_container_name),
    )

    client.create_or_update_data_source_connection(data_source)
    logger.info("Data source ensured: %s", config.data_source_name)


# ---------------------------------------------------------------------------
# Skillset
# ---------------------------------------------------------------------------

def _cognitive_services_account(config: IngestionConfig) -> Optional[CognitiveServicesAccountKey]:
    """
    Return the cognitive services account binding for skillset enrichment.

    None (free tier) → limited to 20 enrichments per indexer run.
    Suitable for sandbox use.  For production, set COGNITIVE_SERVICES_API_KEY
    (retrieved from Key Vault, not stored in code) or transition to
    AIServicesByIdentity once the Search MI has Cognitive Services User role.
    """
    if config.cognitive_services_api_key:
        return CognitiveServicesAccountKey(key=config.cognitive_services_api_key)
    return None  # free tier


def ensure_skillset(config: IngestionConfig, credential: TokenCredential) -> None:
    """
    Create or update the enrichment skillset.

    Skills applied in order:
      1. DocumentExtractionSkill  — extract text and normalised images from raw file data
      2. OcrSkill                 — OCR text from normalised images (scanned / image PDFs)
      3. MergeSkill               — merge native text with OCR text
      4. SplitSkill               — chunk merged text into pages of configurable size
      5. AzureOpenAIEmbeddingSkill — embed each chunk using the configured deployment
    """
    client = SearchIndexerClient(endpoint=config.search_endpoint, credential=credential)

    # 1. DocumentExtractionSkill ─────────────────────────────────────────────
    # Extracts text content and normalised page images from the raw file blob.
    # Requires indexer param allow_skillset_to_read_file_data = True.
    # Supports: PDF, DOCX, XLSX, PPTX, HTML and other common formats.
    document_extraction = DocumentExtractionSkill(
        name="document-extraction",
        description="Extract text and images from the source document",
        inputs=[InputFieldMappingEntry(name="file_data", source="/document/file_data")],
        outputs=[
            OutputFieldMappingEntry(name="content", target_name="extracted_content"),
            OutputFieldMappingEntry(name="normalized_images", target_name="normalised_images"),
        ],
        parsing_mode="default",
        data_to_extract="contentAndMetadata",
        configuration={"imageAction": "generateNormalizedImages", "normalizedImageMaxWidth": 2000, "normalizedImageMaxHeight": 2000},
    )

    # 2. OcrSkill ────────────────────────────────────────────────────────────
    # Runs OCR on each normalised page image.  Handles scanned PDFs and any
    # document page that is stored as a raster image rather than text.
    ocr = OcrSkill(
        name="ocr",
        description="OCR text from normalised page images (scanned / image PDFs)",
        context="/document/normalised_images/*",
        inputs=[InputFieldMappingEntry(name="image", source="/document/normalised_images/*")],
        outputs=[OutputFieldMappingEntry(name="text", target_name="ocr_text")],
        default_language_code="en",
    )

    # 3. MergeSkill ──────────────────────────────────────────────────────────
    # Merges the natively extracted text with the OCR text from images so that
    # the downstream Split and Embed skills see a single unified text body.
    merge = MergeSkill(
        name="merge-text",
        description="Merge native extracted text with OCR text",
        context="/document",
        inputs=[
            InputFieldMappingEntry(name="text", source="/document/extracted_content"),
            InputFieldMappingEntry(
                name="itemsToInsert",
                source="/document/normalised_images/*/ocr_text",
            ),
            InputFieldMappingEntry(
                name="offsets",
                source="/document/normalised_images/*/contentOffset",
            ),
        ],
        outputs=[OutputFieldMappingEntry(name="mergedText", target_name="merged_content")],
        insert_pre_tag="",
        insert_post_tag=" ",
    )

    # 4. SplitSkill ──────────────────────────────────────────────────────────
    # Splits the merged text into overlapping pages (chunks).
    # maximum_page_length and page_overlap_length mirror the local chunking
    # strategy in chunking.py so results are comparable between modes.
    split = SplitSkill(
        name="split",
        description="Split merged text into overlapping chunks",
        context="/document",
        text_split_mode="pages",
        maximum_page_length=config.chunk_size,
        page_overlap_length=config.chunk_overlap,
        inputs=[InputFieldMappingEntry(name="text", source="/document/merged_content")],
        outputs=[OutputFieldMappingEntry(name="textItems", target_name="pages")],
    )

    # 5. AzureOpenAIEmbeddingSkill ───────────────────────────────────────────
    # Generates a dense vector embedding for each chunk.
    # Context is per-page so one embedding is produced per chunk.
    # auth: if azure_openai_api_key is None the search service system-assigned
    # managed identity is used — requires MI to have Cognitive Services OpenAI
    # User role on the Foundry / AI Services account.
    embedding = AzureOpenAIEmbeddingSkill(
        name="embedding",
        description="Embed each text chunk using Azure OpenAI",
        context="/document/pages/*",
        resource_url=config.azure_openai_endpoint,
        deployment_name=config.embedding_deployment_name,
        model_name=config.embedding_deployment_name,
        dimensions=config.embedding_dimensions,
        api_key=config.azure_openai_api_key,
        inputs=[InputFieldMappingEntry(name="text", source="/document/pages/*")],
        outputs=[OutputFieldMappingEntry(name="embedding", target_name="content_vector")],
    )

    # Index projections ──────────────────────────────────────────────────────
    # Project each chunk as a separate Search document.
    # The search service generates a stable chunk-level key (GENERATED_KEY_AS_ID)
    # making re-indexing idempotent.
    index_projections = SearchIndexerIndexProjection(
        selectors=[
            SearchIndexerIndexProjectionSelector(
                target_index_name=config.search_index_name,
                parent_key_field_name="parent_id",
                source_context="/document/pages/*",
                mappings=[
                    InputFieldMappingEntry(name="content", source="/document/pages/*"),
                    InputFieldMappingEntry(
                        name="content_vector",
                        source="/document/pages/*/content_vector",
                    ),
                    InputFieldMappingEntry(
                        name="source_path",
                        source="/document/metadata_storage_path",
                    ),
                    InputFieldMappingEntry(
                        name="source_name",
                        source="/document/metadata_storage_name",
                    ),
                ],
            )
        ],
        parameters=SearchIndexerIndexProjectionsParameters(
            projection_mode=IndexProjectionMode.SKIP_INDEXING_PARENT_DOCUMENTS
        ),
    )

    skillset = SearchIndexerSkillset(
        name=config.skillset_name,
        description="PDF and Excel enrichment: extract → OCR → merge → split → embed",
        skills=[document_extraction, ocr, merge, split, embedding],
        cognitive_services_account=_cognitive_services_account(config),
        index_projection=index_projections,
    )

    client.create_or_update_skillset(skillset)
    logger.info("Skillset ensured: %s", config.skillset_name)


# ---------------------------------------------------------------------------
# Indexer
# ---------------------------------------------------------------------------

def ensure_indexer(config: IngestionConfig, credential: TokenCredential) -> None:
    """Create or update the blob indexer binding the pipeline together."""
    client = SearchIndexerClient(endpoint=config.search_endpoint, credential=credential)

    parameters = IndexingParameters(
        configuration=IndexingParametersConfiguration(
            # Required for DocumentExtractionSkill to receive raw file bytes.
            allow_skillset_to_read_file_data=True,
            # Generate normalised page images so OcrSkill can process them.
            image_action=BlobIndexerImageAction.GENERATE_NORMALIZED_IMAGES,
            # azure-search-documents 11.6.0 injects queryTimeout by default,
            # but Azure Blob indexers reject that property.
            query_timeout=None,
        )
    )

    indexer = SearchIndexer(
        name=config.indexer_name,
        description="Blob indexer for PDF and Excel source documents",
        data_source_name=config.data_source_name,
        target_index_name=config.search_index_name,
        skillset_name=config.skillset_name,
        parameters=parameters,
    )

    client.create_or_update_indexer(indexer)
    logger.info("Indexer ensured: %s", config.indexer_name)


# ---------------------------------------------------------------------------
# Run and monitor
# ---------------------------------------------------------------------------

def run_indexer(config: IngestionConfig, credential: TokenCredential) -> None:
    """Trigger an indexer run."""
    client = SearchIndexerClient(endpoint=config.search_endpoint, credential=credential)
    client.run_indexer(config.indexer_name)
    logger.info("Indexer run triggered: %s", config.indexer_name)


def wait_for_indexer(
    config: IngestionConfig,
    credential: TokenCredential,
    poll_interval_seconds: int = 10,
    timeout_seconds: int = 1800,
) -> dict:
    """
    Poll until the indexer run completes (success or error) and return a
    summary dict with keys: status, items_processed, items_failed, error_message.
    """
    client = SearchIndexerClient(endpoint=config.search_endpoint, credential=credential)
    deadline = time.monotonic() + timeout_seconds

    while time.monotonic() < deadline:
        try:
            status = client.get_indexer_status(config.indexer_name)
        except ResourceNotFoundError:
            logger.warning("Indexer status not yet available, retrying…")
            time.sleep(poll_interval_seconds)
            continue

        run = status.last_result
        if run is None:
            time.sleep(poll_interval_seconds)
            continue

        if run.status in ("success", "transientFailure", "reset"):
            return {
                "status": run.status,
                "items_processed": run.item_count,
                "items_failed": run.failed_item_count,
                "error_message": run.error_message,
            }

        logger.info(
            "Indexer running… status=%s items=%s failed=%s",
            run.status,
            run.item_count,
            run.failed_item_count,
        )
        time.sleep(poll_interval_seconds)

    return {
        "status": "timeout",
        "items_processed": None,
        "items_failed": None,
        "error_message": f"Timed out waiting for indexer after {timeout_seconds}s",
    }
