"""Shared Pydantic request/response models used across query_web endpoints."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    """Request payload for the `/api/ask` endpoint.

    Attributes:
        question: The user's question.
        retrieve_k: The number of documents to retrieve (default is 5).
        controls_context_cap: The maximum number of control context tokens (optional).
        temperature: The sampling temperature for the LLM (default is 1.0).
        top_p: The nucleus sampling parameter for the LLM (default is 1.0).
        auth_token: The authentication token for the request (default is empty).
        thinking_mode: The thinking mode for the LLM (default is "balanced").
        controls_semantic: Whether to use semantic search for controls (optional).
        controls_framework: The specific controls framework to filter by (optional).
        controls_comparison_mode: The comparison mode for controls (default is "auto-detect").
        evidence_corpora_include: List of evidence corpora to include (optional).
        evidence_corpora_exclude: List of evidence corpora to exclude (optional).
        max_completion_tokens: The maximum number of tokens for the LLM completion (optional).
        evaluator_max_completion_tokens: The maximum number of tokens for the evaluator completion (optional).
        advanced_mode: Whether to enable advanced mode features (default is False).
    """

    question: str
    retrieve_k: int = Field(default=5, ge=1, le=20)
    controls_context_cap: int | None = Field(default=None, ge=1, le=2000)
    temperature: float = Field(default=1.0, ge=0.0, le=1.0)
    top_p: float = Field(default=1.0, ge=0.0, le=1.0)
    auth_token: str = ""
    thinking_mode: str = "balanced"
    controls_semantic: bool | None = None
    controls_framework: str | None = None
    controls_comparison_mode: str = "auto-detect"
    evidence_corpora_include: list[str] | None = None
    evidence_corpora_exclude: list[str] | None = None
    max_completion_tokens: int | None = Field(default=None, ge=256, le=8192)
    evaluator_max_completion_tokens: int | None = Field(default=None, ge=128, le=4096)
    advanced_mode: bool = False


class AskResponse(BaseModel):
    """Structured response returned by ask and RAG endpoints.

    Attributes:
        answer: The answer generated by the LLM.
        results: A list of result dictionaries.
        controls_results: A list of control result dictionaries (default is empty).
        controls_debug: Debug information for controls (optional).
        evaluation: Evaluation results (optional).
        iterations: The number of LLM iterations performed (optional).
        metrics: Timing metrics from the RAG pipeline (optional).
        audit: Audit information (optional).
        error: Error message, if any.
    """

    answer: str
    results: list[dict[str, Any]]
    controls_results: list[dict[str, Any]] = []
    controls_debug: dict[str, Any] | None = None
    evaluation: dict[str, Any] | None = None
    iterations: int | None = None
    metrics: dict[str, float] | None = None
    audit: dict[str, Any] | None = None
    error: str | None = None
