# Generated by phase1-bootstrap.sh — do not edit manually.
bucket         = "tfstate-rag-dev-f45447a1"
key            = "aws/dev/terraform.tfstate"
region         = "ap-southeast-2"
use_lockfile   = true
encrypt        = true
