# Generated by phase1-bootstrap.sh — do not edit manually.
bucket         = "tfstate-rag-dev-253b2b03"
key            = "aws/dev/terraform.tfstate"
region         = "ap-southeast-2"
dynamodb_table = "tfstate-lock-rag-dev"
encrypt        = true
