#!/usr/bin/env bash
# Bootstraps AWS remote Terraform state (S3 bucket + DynamoDB lock table) and
# writes the backend configuration file consumed by subsequent terraform init calls.
#
# Usage:
#   ./ops/scripts/aws/phase1-bootstrap.sh <env>
#
# Environment variable overrides:
#   AWS_REGION           (default: ap-southeast-2)
#   TF_PROJECT           (default: rag)
#   TF_BACKEND_KEY       (default: aws/<env>/terraform.tfstate)
set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  cat <<'EOF'
Usage:
  ./ops/scripts/aws/phase1-bootstrap.sh <env>

Bootstraps AWS remote Terraform state and writes:
  - infra/terraform/aws/environments/<env>/backend.hcl

Supported environments:
  dev, test, prod

Optional env var overrides:
  AWS_REGION     Target AWS region           (default: ap-southeast-2)
  TF_PROJECT     Project name in naming      (default: rag)
  TF_BACKEND_KEY S3 key for main stack state (default: aws/<env>/terraform.tfstate)
  TF_ENABLE_BOOTSTRAP_SECRETS_MANAGER       (default: true)
EOF
  exit 0
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
BOOTSTRAP_DIR="${ROOT_DIR}/infra/terraform/aws/bootstrap"

ENVIRONMENT="${1:-dev}"
case "${ENVIRONMENT}" in
  dev|test|prod) ;;
  *)
    echo "Unsupported environment '${ENVIRONMENT}'. Use one of: dev, test, prod." >&2
    exit 1
    ;;
esac

AWS_REGION="${AWS_REGION:-ap-southeast-2}"
TF_PROJECT="${TF_PROJECT:-rag}"
TF_BACKEND_KEY="${TF_BACKEND_KEY:-aws/${ENVIRONMENT}/terraform.tfstate}"
TF_ENABLE_BOOTSTRAP_SECRETS_MANAGER="${TF_ENABLE_BOOTSTRAP_SECRETS_MANAGER:-true}"
BACKEND_FILE="${ROOT_DIR}/infra/terraform/aws/environments/${ENVIRONMENT}/backend.hcl"

if ! command -v terraform >/dev/null 2>&1; then
  echo "ERROR: terraform is required in PATH." >&2
  exit 1
fi

if ! command -v aws >/dev/null 2>&1; then
  echo "ERROR: AWS CLI is required in PATH." >&2
  exit 1
fi

echo "==> Verifying AWS credentials"
if ! aws sts get-caller-identity >/dev/null 2>&1; then
  echo "ERROR: AWS CLI is not authenticated." >&2
  echo "Run: aws configure  (or set AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_PROFILE)" >&2
  exit 1
fi

ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
echo "    Account: ${ACCOUNT_ID}  Region: ${AWS_REGION}"

echo "==> Running bootstrap Terraform in ${BOOTSTRAP_DIR}"
pushd "${BOOTSTRAP_DIR}" >/dev/null

terraform init -input=false

terraform apply \
  -input=false \
  -auto-approve \
  -var="aws_region=${AWS_REGION}" \
  -var="project=${TF_PROJECT}" \
  -var="environment=${ENVIRONMENT}" \
  -var="enable_bootstrap_secrets_manager=${TF_ENABLE_BOOTSTRAP_SECRETS_MANAGER}"

STATE_BUCKET="$(terraform output -raw state_bucket_name)"
LOCK_TABLE="$(terraform output -raw lock_table_name)"

popd >/dev/null

echo "==> Writing backend configuration to ${BACKEND_FILE}"
mkdir -p "$(dirname "${BACKEND_FILE}")"
cat >"${BACKEND_FILE}" <<EOF
# Generated by phase1-bootstrap.sh — do not edit manually.
bucket         = "${STATE_BUCKET}"
key            = "${TF_BACKEND_KEY}"
region         = "${AWS_REGION}"
dynamodb_table = "${LOCK_TABLE}"
encrypt        = true
EOF

echo ""
echo "==> Bootstrap complete."
echo "    State bucket : ${STATE_BUCKET}"
echo "    Lock table   : ${LOCK_TABLE}"
echo "    Backend file : ${BACKEND_FILE}"
echo ""
echo "==> Next step — initialise the main stack:"
echo "    cd infra/terraform/aws"
echo "    terraform init -backend-config=environments/${ENVIRONMENT}/backend.hcl"
echo "    terraform plan -var-file=environments/${ENVIRONMENT}/${ENVIRONMENT}.tfvars"
