bootstrap_state_storage_account_name = "sttfstatedevdt5os7"
bootstrap_state_storage_account_resource_group_name = "rg-tfstate-dev"
bootstrap_key_vault_name = "kvtfstatedt5os7"
bootstrap_key_vault_resource_group_name = "rg-tfstate-dev"
jumpbox_ssh_public_key_secret_name = "jumpbox-admin-ssh-public-key-dev"
