subscription_id              = "<set-me>"
location                     = "australiaeast"
location_short               = "aue"
environment                  = "dev"
resource_group_name          = "rg-ai-platform-dev"
vnet_cidr                    = "10.20.0.0/16"
private_endpoint_subnet_cidr = "10.20.1.0/24"
agent_subnet_cidr            = "10.20.2.0/24"
container_apps_subnet_cidr   = "10.20.5.0/24"
jumpbox_subnet_cidr          = "10.20.3.0/24"
azure_bastion_subnet_cidr    = "10.20.4.0/26"
jumpbox_admin_ssh_public_key = "<set-me-ssh-public-key>"
jumpbox_vm_size              = "Standard_B2as_v2"
enable_model_deployments     = true
enable_ingestion_job         = true
enable_query_web_app         = true
query_web_image_tag          = "latest"
search_index_name            = "grounding-index"
query_top_k                  = 5
query_default_temperature    = 1.0
query_eval_threshold         = 0.72
# Optional shared token for query web app auth gate.
# query_web_auth_token       = "change-me"
